services:
  - type: web
    name: how-are-we-crazy-playtest
    runtime: node
    region: frankfurt
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    numInstances: 1
